[build]
  publish = "dist"
  command = "npm run build"

# フォーム送信時の言語設定
[context.production.environment]
  NETLIFY_FORMS_LANGUAGE = "ja"

[[forms]]
  name = "contact-form"
  
  [forms.settings]
    # カスタム成功ページ（オプション）
    # success_action = "/success"
    # スパム対策
    spam_detection = true
    
  # 運営側への通知メール設定
  [forms.notifications.email]
    to = ["info@marineblue.jp"]
    from = "noreply@marineblue.jp"
    subject = "【マリンブルー公式サイト】新しいお問い合わせがあります"
    body = """
【マリンブルー公式サイトからのお問い合わせ】

お客様情報：
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
お名前：{{ name }}
メールアドレス：{{ email }}
電話番号：{{ phone }}
お問い合わせ内容：{{ subject }}

メッセージ：
{{ message }}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

送信日時：{{ sent_date }}
送信元：マリンブルー公式サイト (https://marineblue.jp)

※このメールはマリンブルー公式サイトのお問い合わせフォームから自動送信されています。
※お客様への返信をお忘れなくお願いいたします。
"""

  # お客様への自動返信メール設定
  [[forms.notifications.email]]
    to = ["{{ email }}"]
    from = "info@marineblue.jp"
    reply_to = "info@marineblue.jp"
    subject = "【マリンブルー】お問い合わせありがとうございます"
    body = """
{{ name }} 様

この度は、マリンブルー公式サイトよりお問い合わせをいただき、誠にありがとうございます。

以下の内容でお問い合わせを承りました：
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
お名前：{{ name }}
メールアドレス：{{ email }}
電話番号：{{ phone }}
お問い合わせ内容：{{ subject }}

メッセージ：
{{ message }}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

お問い合わせ受付日時：{{ sent_date }}

担当者より2営業日以内にご連絡させていただきます。
お急ぎの場合は、お電話（090-6845-2863）にてお問い合わせください。

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
マリンブルー
〒静岡県熱海市
電話：090-6845-2863
メール：info@marineblue.jp
ウェブサイト：https://marineblue.jp

※このメールは自動配信されています。
※このメールに心当たりがない場合は、お手数ですが削除をお願いいたします。
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""

[[forms]]
  name = "estimate-form"
  
  [forms.settings]
    # カスタム成功ページ（オプション）
    # success_action = "/success"
    # スパム対策
    spam_detection = true
    
  # 運営側への通知メール設定
  [forms.notifications.email]
    to = ["info@marineblue.jp"]
    from = "noreply@marineblue.jp"
    subject = "【マリンブルー公式サイト】新しいお見積り依頼があります"
    body = """
【マリンブルー公式サイトからのお見積り依頼】

お客様情報：
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
お名前：{{ name }}
メールアドレス：{{ email }}
電話番号：{{ phone }}
ご希望プラン：{{ plan }}
参加人数：{{ participants }}名
ご希望日：{{ preferredDate }}

ご要望・ご質問：
{{ requests }}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

送信日時：{{ sent_date }}
送信元：マリンブルー公式サイト (https://marineblue.jp)

※このメールはマリンブルー公式サイトのお見積りフォームから自動送信されています。
※お客様への返信をお忘れなくお願いいたします。
"""

  # お客様への自動返信メール設定
  [[forms.notifications.email]]
    to = ["{{ email }}"]
    from = "info@marineblue.jp"
    reply_to = "info@marineblue.jp"
    subject = "【マリンブルー】お見積り依頼ありがとうございます"
    body = """
{{ name }} 様

この度は、マリンブルー公式サイトよりお見積り依頼をいただき、誠にありがとうございます。

以下の内容でお見積り依頼を承りました：
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
お名前：{{ name }}
メールアドレス：{{ email }}
電話番号：{{ phone }}
ご希望プラン：{{ plan }}
参加人数：{{ participants }}名
ご希望日：{{ preferredDate }}

ご要望・ご質問：
{{ requests }}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

お見積り依頼受付日時：{{ sent_date }}

担当者より2営業日以内に詳細なお見積りをお送りいたします。
お急ぎの場合は、お電話（090-6845-2863）にてお問い合わせください。

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
マリンブルー
〒静岡県熱海市
電話：090-6845-2863
メール：info@marineblue.jp
ウェブサイト：https://marineblue.jp

※このメールは自動配信されています。
※このメールに心当たりがない場合は、お手数ですが削除をお願いいたします。
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""
