[build]
  publish = "dist"
  command = "npm run build"

[[forms]]
  name = "contact-form"
  
  [forms.settings]
    # カスタム成功ページ（オプション）
    # success_action = "/success"
    
  # メール通知設定
  [forms.notifications.email]
    to = ["info@marineblue.jp"]
    subject = "【マリンブルー公式サイト】新しいお問い合わせがあります"
    body = """
【マリンブルー公式サイトからのお問い合わせ】

お客様情報：
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
お名前：{{ name }}
メールアドレス：{{ email }}
電話番号：{{ phone }}
お問い合わせ内容：{{ subject }}

メッセージ：
{{ message }}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

送信日時：{{ sent_date }}
送信元：マリンブルー公式サイト (https://marineblue.jp)

※このメールはマリンブルー公式サイトのお問い合わせフォームから自動送信されています。
※お客様への返信をお忘れなくお願いいたします。
"""

[[forms]]
  name = "estimate-form"
  
  [forms.settings]
    # カスタム成功ページ（オプション）
    # success_action = "/success"
    
  # メール通知設定
  [forms.notifications.email]
    to = ["info@marineblue.jp"]
    subject = "【マリンブルー公式サイト】新しいお見積り依頼があります"
    body = """
【マリンブルー公式サイトからのお見積り依頼】

お客様情報：
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
お名前：{{ name }}
メールアドレス：{{ email }}
電話番号：{{ phone }}
ご希望プラン：{{ plan }}
参加人数：{{ participants }}名
ご希望日：{{ preferredDate }}

ご要望・ご質問：
{{ requests }}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

送信日時：{{ sent_date }}
送信元：マリンブルー公式サイト (https://marineblue.jp)

※このメールはマリンブルー公式サイトのお見積りフォームから自動送信されています。
※お客様への返信をお忘れなくお願いいたします。
"""
